### ISSUE TITLE
Render vcl in utf-8 instand of asci

### ISSUE THREAD

**Issue by jtaczanowski** [allegro/vaas#133]
```
Traceback (most recent call last):
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/vaas/cluster/cluster.py", line 33, in load_vcl_task
    return VarnishCluster().load_vcl(start_processing_time, clusters)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/vaas/cluster/cluster.py", line 50, in load_vcl
    vcl_list = ParallelRenderer(self.max_workers).render_vcl_for_servers(start_processing_time.isoformat(), servers)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/vaas/cluster/cluster.py", line 136, in render_vcl_for_servers
    vcl_list.append(tuple([server, future_result.result()]))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 397, in result
    return self.__get_result()
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0107' in position 427071: ordinal not in range(128)ESC[0m
```

**Comment by awmackowiak** [comment]
Old issue. Closed.
